### ISSUE TITLE
Update "install_requires" from aiida to aiida-core

### ISSUE THREAD

**Issue by chrisjsewell** [aiidateam/aiida-plugin-cutter#20]
One of the major reasons to do this is that readthedocs builds seem to fail with aiida (https://readthedocs.org/projects/aiida-crystal17/builds/7693840/) but not with aiida-core

I'd also note that, for some reason I get an `ImportError` for `pgtest` during tests, unless I specifically but it in the requirements (even though it seems to be in the aiida-core[testing] requirements?)
 
```json
{
    "install_requires": [
        "aiida-core>=0.12.0,<1.0.0"
    ],
    "extras_require": {
        "testing": [
            "aiida-core[testing]",
            "wheel>=0.31",
            "pgtest"
        ]
   }
}
```

**Comment by ltalirz** [comment]
Thanks a lot for these suggestions, will look into this!

**Comment by ltalirz** [comment]
I can [reproduce the pgtest import error](https://travis-ci.org/aiidateam/aiida-diff/jobs/421218412#L634)

The travis log shows that `pgtest` is not installed (nor are any other "testing" dependencies of `aiida-core`).
This is not the fault of the [aiida-core wheel used](https://files.pythonhosted.org/packages/84/27/2d13034a4100eff643d0d70b8f7d0722599007f402022b21d0e106764b48/aiida_core-0.12.1-py2-none-any.whl), whose METADATA contains the line
```
Requires-Dist: pgtest (==1.1.0); extra == 'testing'
```
It turns out that putting the same dependcy with different extras is an [unresolved pip issue](https://github.com/pypa/pip/issues/4957).
It means we will need to replicate the dependencies needed for testing.
